#+TITLE: Brexit
#+AUTHOR: Pierre Mercatoris
#+PROPERTY: header-args:R  :session *brexit*
#+PROPERTY: header-args cache yes 
#+PROPERTY: header-args exports results
#+OPTIONS: ^:nil

#+BEGIN_SRC R :exports none
  rm(list = ls())
  library(ggplot2)
  library(pastecs)
  library(ascii)
  library(GGally)
                                          # allows to export tables to org
  options(asciiType="org")
  brexit <- read.csv("data/DataBrexit.csv")
                                          # remove warnings from outputs
  options(warn=-1)
                                          # options(warn=0)
#+END_SRC

#+RESULTS:
: 0

* TODO Introduction (1 page max., 0.5 pt)[0/3]
 - [ ] Describe briefly the topic of the Project and the motivations (which kind of information or evidences would you like to find out).
 - [ ] Describe briefly the data set: source and what are the data about.
 - [ ] define what is your target population and what is your sample (in the case that they are different). give the total sample size.

 
* TODO Description of variables and recoding (2 page max., 0.5 pt) [3/3]
  - [X] Describe each of the variables that you will analyze in this project. What are they and how are they measured.
  - [X] Mention the type of each variable, saying if it is qualitative or quantitative, and daulaepending on the case, nominal/ordinal or discrete/continuous.
  - [X] For variables with too many categories, try to reduce the number of categories by merging categories with similar meaning and recoding them. With fewer categories, interpretation is easier.
  
| Variable         | What?                   | How?                                 | Type                    |
|------------------+-------------------------+--------------------------------------+-------------------------|
| Region           | 12 regions of UK        | Wales, Scotland and Northern Ireland | Qualitative nominal     |
|                  |                         | are considered regions               |                         |
| Area             | Local authorities of UK | Brexit referendum                    | Qualitative nominal     |
| Pct_Leave        | % of vote to leave EU   | Brexit referendum                    | Quantitative continuous |
| Mean.Age         | Mean age                | Age on 27th March 2011               | Quantitative continuous |
|                  |                         | Census 2011                          |                         |
| NoQualification  | % without any diploma   | Census 2011                          | Quantitative continuous |
| UniQualification | % with uni degree       | Census 2011                          | Quantitative continuous |
| Fluent           | % English proficient    | Census 2011                          | Quantitative continuous |
| Won.Parliament   | Party leading EPE       | EPE 2014                             | Qualitative nominal     |

** Reducing NoQualification

In order to have 3 qualitative and 3 quantitative variables to analyse alongside Pct_Leave, NoQualification was categorised into 3 groups (High, Medium and Low), transforming it into a qualitative ordinal variable. This variable was chosen its distribution (fig. [[fig:noQualDis]]) is normal and can be split relatively equally around the mean (\mu) using its standard deviation (\sigma). All values $x$ where, $ x > \mu + 0.5 \sigma$ were considered as High, $\mu - 0.5 \sigma < x < \mu + 0.5 \sigma$ considered Medium and $x < \mu - 0.5 \sigma$ considered Low.  

#+BEGIN_SRC R :results output graphics :file "./pictures/noQualDis.svg" 
  x <- mean(brexit$NoQualification,na.rm = T)
  ggplot(brexit,aes(NoQualification))+
    geom_histogram(aes(y = ..density..))+
    geom_density()+
                                          # Add lines on mean +- sd
    geom_vline(linetype = 2,xintercept = mean(brexit$NoQualification,na.rm = T)+0.5*sd(brexit$NoQualification,na.rm = T),color="red")+
    geom_vline(linetype = 2, xintercept = mean(brexit$NoQualification,na.rm = T)-0.5*sd(brexit$NoQualification,na.rm = T),color="red")+
    labs( x = "% of population holding no qualification", y = "Density")

#+END_SRC

#+NAME: fig:noQualDis
#+CAPTION: Density plot and histogram of the % of the population holding no qualification. The red dotted lines show the split for the reduction to High, Medium, Low.
#+RESULTS:
[[file:./pictures/noQualDis.svg]]

#+BEGIN_SRC R :exports none
  # categorise the data and label it
  brexit$NoQualification <- cut(brexit$NoQualification,c(0,mean(brexit$NoQualification,na.rm = T)-0.5*sd(brexit$NoQualification,na.rm = T),mean(brexit$NoQualification,na.rm = T)+0.5*sd(brexit$NoQualification,na.rm = T),max(brexit$NoQualification,na.rm=T)),labels=c("Low","Medium","High"))
  head(brexit$NoQualification)
#+END_SRC

#+RESULTS:
| Medium |
| Medium |
| Medium |
| High   |
| Low    |
| Low    |

* TODO Univariariate description (3 pages max., 2 pt)[2/2]
   - [X] Qualitative variables: Frequency tables, Barplots or Piechars.
   - [X] Quantitative variables: Frequency tables (intervals if continuous). Location measures (mean, median, quartiles), dispersion measures (variance, std. dev., CV, range, IQR), shape measures (asymmetry coefficients), Histogram or Boxplot.

  #+BEGIN_SRC R :results output raw
    ascii(summary(brexit[,-2],maxsum=12))
  #+END_SRC

  #+RESULTS:
  |    | Region                      | Pct_Leave     | Mean.Age      | NoQualification | UniQualification | Fluent        | Won.Parliament |
  |----+-----------------------------+---------------+---------------+-----------------+------------------+---------------+----------------|
  |  1 | East                    :47 | Min.   : 4.09 | Min.   :30.93 | Low   :124      | Min.   :14.00    | Min.   :59.00 | Con : 84       |
  |  2 | East Midlands           :40 | 1st Qu.:47.14 | 1st Qu.:38.79 | Medium:132      | 1st Qu.:22.00    | 1st Qu.:92.00 | Lab :100       |
  |  3 | London                  :33 | Median :54.27 | Median :40.39 | High  :114      | Median :26.00    | Median :96.00 | LD  :  4       |
  |  4 | North East              :12 | Mean   :52.99 | Mean   :40.32 | NA's  : 12      | Mean   :26.68    | Mean   :93.63 | SNP : 16       |
  |  5 | Northern Ireland        : 1 | 3rd Qu.:60.34 | 3rd Qu.:42.19 |                 | 3rd Qu.:31.00    | 3rd Qu.:98.00 | UKIP:173       |
  |  6 | North West              :39 | Max.   :75.56 | Max.   :47.69 |                 | Max.   :54.00    | Max.   :99.00 | NA's:  5       |
  |  7 | Scotland                :32 |               | NA's   :12    |                 | NA's   :12       | NA's   :12    |                |
  |  8 | South East              :67 |               |               |                 |                  |               |                |
  |  9 | South West              :38 |               |               |                 |                  |               |                |
  | 10 | Wales                   :22 |               |               |                 |                  |               |                |
  | 11 | West Midlands           :30 |               |               |                 |                  |               |                |
  | 12 | Yorkshire and The Humber:21 |               |               |                 |                  |               |                |

** Qualitative variables


#+BEGIN_SRC R :results output graphics :file "./pictures/regionPie.svg"
  ggplot(brexit,aes(Region))+
    geom_bar(width = 1)+
    coord_polar()+
    labs( x = "Region", y = "Number of localities")
    # guides(fill=FALSE)
#+END_SRC

#+RESULTS:
[[file:./pictures/regionPie.svg]]

#+BEGIN_SRC R  :results output graphics :file "./pictures/noQualBar.svg"
  ggplot(brexit,aes(NoQualification,fill = NoQualification))+
    geom_bar()+
    labs( x = "Level of unqualification", y = "Number of localities")+
    guides(fill=FALSE)
#+END_SRC

#+RESULTS:
[[file:./pictures/noQualBar.svg]]

#+BEGIN_SRC R  :results graphics :file "./pictures/epeBar.svg"
  ggplot(na.omit(brexit),aes(Won.Parliament,fill = Won.Parliament))+
    geom_bar()+
    labs( x = "Leading party during EPE of 2014", y = "Number of localities")+
    guides(fill=FALSE)

#+END_SRC

#+RESULTS:
[[file:./pictures/epeBar.svg]]

** Quantitative variables
#+BEGIN_SRC R :results output raw 
ascii(stat.desc(brexit[c("Pct_Leave","Mean.Age","UniQualification")],norm = TRUE, p = 0.95))
#+END_SRC

#+RESULTS:
|              | Pct_Leave | Mean.Age | UniQualification |
|--------------+-----------+----------+------------------|
| nbr.val      |    382.00 |   370.00 |           370.00 |
| nbr.null     |      0.00 |     0.00 |             0.00 |
| nbr.na       |      0.00 |    12.00 |            12.00 |
| min          |      4.09 |    30.93 |            14.00 |
| max          |     75.56 |    47.69 |            54.00 |
| range        |     71.47 |    16.75 |            40.00 |
| sum          |  20241.80 | 14918.74 |          9873.00 |
| median       |     54.27 |    40.39 |            26.00 |
| mean         |     52.99 |    40.32 |            26.68 |
| SE.mean      |      0.55 |     0.15 |             0.38 |
| CI.mean.0.95 |      1.08 |     0.29 |             0.74 |
| var          |    114.42 |     8.08 |            52.93 |
| std.dev      |     10.70 |     2.84 |             7.28 |
| coef.var     |      0.20 |     0.07 |             0.27 |
| skewness     |     -0.82 |    -0.33 |             0.93 |
| skew.2SE     |     -3.30 |    -1.30 |             3.67 |
| kurtosis     |      1.09 |     0.37 |             1.16 |
| kurt.2SE     |      2.19 |     0.73 |             2.30 |
| normtest.W   |      0.96 |     0.99 |             0.95 |
| normtest.p   |      0.00 |     0.01 |             0.00 |

#+BEGIN_SRC R :results graphics :file "./pictures/uniQualDis.svg"
  ggplot(brexit,aes(UniQualification))+
    geom_histogram(aes(y = ..density..))+
    geom_density()+
    labs( x = "% of population holding university qualification", y = "Density")
#+END_SRC

#+NAME: graphic1
#+CAPTION: Hello
#+RESULTS:
[[file:./pictures/uniQualDis.svg]]

#+BEGIN_SRC R :results graphics :file "./pictures/ageDis.svg"
  ggplot(brexit,aes(Mean.Age))+
    geom_histogram(aes(y = ..density..))+
    geom_density()+
    labs( x = "Mean age", y = "Density")
#+END_SRC

#+RESULTS:
[[file:./pictures/ageDis.svg]]

#+BEGIN_SRC R :results graphics :file "./pictures/fluentDis.svg"
  ggplot(brexit,aes(Fluent))+
    geom_histogram(aes(y = ..density..))+
    geom_density()+
    labs( x = "% of population fluent in English", y = "Density")

#+END_SRC

#+RESULTS:
[[file:./pictures/fluentDis.svg]]

#+BEGIN_SRC R  :results graphics :file "./pictures/leavePctDis.svg"
  ggplot(brexit,aes(Pct_Leave))+
    geom_histogram(aes(y = ..density..))+
    geom_density()+
    labs( x = "% that voted to leave at Brexit", y = "Density")
#+END_SRC

#+RESULTS:
[[file:./pictures/leavePctDis.svg]]

* TODO Bivariate description (5 pages max., 2 pt)[3/3]

 - [X] Both variables qualitative: Crossclassified table, tables with interesting conditional distributions, grouped or stacked barplots for those conditionals. Compare proportions in different groups.
 - [X] One qualitative, one quantitative: Compare the means, variances and CVs of the quantitative variable for each category of the other one. Compare histograms or boxplots of the quantitative variable for each category of the other one.
 - [X] Both quantitative: scatterplot, covariance, Pearson correlation coef., regression line of a target variable in terms of one/several explanatory variables.

** Both qualitative 

#+BEGIN_SRC R :results output raw
  ascii(CrossTable(brexit$Won.Parliament,brexit$NoQualification))
#+END_SRC

#+RESULTS:
Error in ascii(CrossTable(brexit$Won.Parliament, brexit$NoQualification)) : 
  could not find function "CrossTable"

 
   Cell Contents
|-------------------------|
|                       N |
| Chi-square contribution |
|           N / Row Total |
|           N / Col Total |
|         N / Table Total |
|-------------------------|

 
Total Observations in Table:  367 

 
                      | brexit$NoQualification 
brexit$Won.Parliament |       Low |    Medium |      High | Row Total | 
----------------------|-----------|-----------|-----------|-----------|
                  Con |        64 |        13 |         3 |        80 | 
                      |    52.614 |     8.474 |    19.212 |           | 
                      |     0.800 |     0.163 |     0.037 |     0.218 | 
                      |     0.525 |     0.099 |     0.026 |           | 
                      |     0.174 |     0.035 |     0.008 |           | 
----------------------|-----------|-----------|-----------|-----------|
                  Lab |        27 |        25 |        46 |        98 | 
                      |     0.955 |     2.848 |     7.952 |           | 
                      |     0.276 |     0.255 |     0.469 |     0.267 | 
                      |     0.221 |     0.191 |     0.404 |           | 
                      |     0.074 |     0.068 |     0.125 |           | 
----------------------|-----------|-----------|-----------|-----------|
                   LD |         1 |         1 |         1 |         3 | 
                      |     0.000 |     0.005 |     0.005 |           | 
                      |     0.333 |     0.333 |     0.333 |     0.008 | 
                      |     0.008 |     0.008 |     0.009 |           | 
                      |     0.003 |     0.003 |     0.003 |           | 
----------------------|-----------|-----------|-----------|-----------|
                  SNP |         2 |         5 |         9 |        16 | 
                      |     2.071 |     0.089 |     3.268 |           | 
                      |     0.125 |     0.312 |     0.562 |     0.044 | 
                      |     0.016 |     0.038 |     0.079 |           | 
                      |     0.005 |     0.014 |     0.025 |           | 
----------------------|-----------|-----------|-----------|-----------|
                 UKIP |        28 |        87 |        55 |       170 | 
                      |    14.385 |    11.415 |     0.091 |           | 
                      |     0.165 |     0.512 |     0.324 |     0.463 | 
                      |     0.230 |     0.664 |     0.482 |           | 
                      |     0.076 |     0.237 |     0.150 |           | 
----------------------|-----------|-----------|-----------|-----------|
         Column Total |       122 |       131 |       114 |       367 | 
                      |     0.332 |     0.357 |     0.311 |           | 
----------------------|-----------|-----------|-----------|-----------|

 
- 64
- 0.8
- 0.524590163934426
- 0.174386920980926

 
   Cell Contents
|-------------------------|
|                       N |
| Chi-square contribution |
|           N / Row Total |
|           N / Col Total |
|         N / Table Total |
|-------------------------|

 
Total Observations in Table:  367 

 
                      | brexit$NoQualification 
brexit$Won.Parliament |       Low |    Medium |      High | Row Total | 
----------------------|-----------|-----------|-----------|-----------|
                  Con |        64 |        13 |         3 |        80 | 
                      |    52.614 |     8.474 |    19.212 |           | 
                      |     0.800 |     0.163 |     0.037 |     0.218 | 
                      |     0.525 |     0.099 |     0.026 |           | 
                      |     0.174 |     0.035 |     0.008 |           | 
----------------------|-----------|-----------|-----------|-----------|
                  Lab |        27 |        25 |        46 |        98 | 
                      |     0.955 |     2.848 |     7.952 |           | 
                      |     0.276 |     0.255 |     0.469 |     0.267 | 
                      |     0.221 |     0.191 |     0.404 |           | 
                      |     0.074 |     0.068 |     0.125 |           | 
----------------------|-----------|-----------|-----------|-----------|
                   LD |         1 |         1 |         1 |         3 | 
                      |     0.000 |     0.005 |     0.005 |           | 
                      |     0.333 |     0.333 |     0.333 |     0.008 | 
                      |     0.008 |     0.008 |     0.009 |           | 
                      |     0.003 |     0.003 |     0.003 |           | 
----------------------|-----------|-----------|-----------|-----------|
                  SNP |         2 |         5 |         9 |        16 | 
                      |     2.071 |     0.089 |     3.268 |           | 
                      |     0.125 |     0.312 |     0.562 |     0.044 | 
                      |     0.016 |     0.038 |     0.079 |           | 
                      |     0.005 |     0.014 |     0.025 |           | 
----------------------|-----------|-----------|-----------|-----------|
                 UKIP |        28 |        87 |        55 |       170 | 
                      |    14.385 |    11.415 |     0.091 |           | 
                      |     0.165 |     0.512 |     0.324 |     0.463 | 
                      |     0.230 |     0.664 |     0.482 |           | 
                      |     0.076 |     0.237 |     0.150 |           | 
----------------------|-----------|-----------|-----------|-----------|
         Column Total |       122 |       131 |       114 |       367 | 
                      |     0.332 |     0.357 |     0.311 |           | 
----------------------|-----------|-----------|-----------|-----------|

 
- 64
- 0.8
- 0.524590163934426
- 0.174386920980926

 
   Cell Contents
|-------------------------|
|                       N |
| Chi-square contribution |
|           N / Row Total |
|           N / Col Total |
|         N / Table Total |
|-------------------------|NoQualificaiton

 
Total Observations in Table:  367 

 
                      | brexit$NoQualification 
brexit$Won.Parliament |       Low |    Medium |      High | Row Total | 
----------------------|-----------|-----------|-----------|-----------|
                  Con |        64 |        13 |         3 |        80 | 
                      |    52.614 |     8.474 |    19.212 |           | 
                      |     0.800 |     0.163 |     0.037 |     0.218 | 
                      |     0.525 |     0.099 |     0.026 |           | 
                      |     0.174 |     0.035 |     0.008 |           | 
----------------------|-----------|-----------|-----------|-----------|
                  Lab |        27 |        25 |        46 |        98 | 
                      |     0.955 |     2.848 |     7.952 |           | 
                      |     0.276 |     0.255 |     0.469 |     0.267 | 
                      |     0.221 |     0.191 |     0.404 |           | 
                      |     0.074 |     0.068 |     0.125 |           | 
----------------------|-----------|-----------|-----------|-----------|
                   LD |         1 |         1 |         1 |         3 | 
                      |     0.000 |     0.005 |     0.005 |           | 
                      |     0.333 |     0.333 |     0.333 |     0.008 | 
                      |     0.008 |     0.008 |     0.009 |           | 
                      |     0.003 |     0.003 |     0.003 |           | 
----------------------|-----------|-----------|-----------|-----------|
                  SNP |         2 |         5 |         9 |        16 | 
                      |     2.071 |     0.089 |     3.268 |           | 
                      |     0.125 |     0.312 |     0.562 |     0.044 | 
                      |     0.016 |     0.038 |     0.079 |           | 
                      |     0.005 |     0.014 |     0.025 |           | 
----------------------|-----------|-----------|-----------|-----------|
                 UKIP |        28 |        87 |        55 |       170 | 
                      |    14.385 |    11.415 |     0.091 |           | 
                      |     0.165 |     0.512 |     0.324 |     0.463 | 
                      |     0.230 |     0.664 |     0.482 |           | 
                      |     0.076 |     0.237 |     0.150 |           | 
----------------------|-----------|-----------|-----------|-----------|
         Column Total |       122 |       131 |       114 |       367 | 
                      |     0.332 |     0.357 |     0.311 |           | 
----------------------|-----------|-----------|-----------|-----------|

#+BEGIN_SRC R :exports results :results output raw
  ascii(ftable(table(brexit$Won.Parliament,brexit$NoQualification)))

#+END_SRC

#+RESULTS:
|      |   | Low | Medium | High |
|------+---+-----+--------+------|
|      |   |     |        |      |
| Con  |   |  64 |     13 |    3 |
| Lab  |   |  27 |     25 |   46 |
| LD   |   |   1 |      1 |    1 |
| SNP  |   |   2 |      5 |    9 |
| UKIP |   |  28 |     87 |   55 |

#+BEGIN_SRC R :results graphics :file "./pictures/epeNoQualBar.svg"
  ggplot(na.omit(brexit),aes(Won.Parliament))+
    geom_bar(aes(fill = NoQualification),position="fill")+
    theme(axis.text.x = element_text(angle = 90, hjust = 1))
#+END_SRC

#+RESULTS:
[[file:./pictures/epeNoQualBar.svg]]
 
#+BEGIN_SRC R :results graphics :file "./pictures/epeRegionBar.svg"
  ggplot(na.omit(brexit),aes(Region))+
    geom_bar(aes(fill = Won.Parliament),position="fill")+
    theme(axis.text.x = element_text(angle = 90, hjust = 1))
#+END_SRC

#+RESULTS:
[[file:./pictures/epeRegionBar.svg]]

#+BEGIN_SRC R :results graphics :file "./pictures/noQualRegionBar.svg"
  ggplot(na.omit(brexit),aes(Region))+
    geom_bar(aes(fill = NoQualification),position="fill")+
    theme(axis.text.x = element_text(angle = 90, hjust = 1))
#+END_SRC

#+RESULTS:
[[file:./pictures/noQualRegionBar.svg]]


** Qualitative and Quantitative

#+BEGIN_SRC R :results graphics :file "./pictures/QualQuanMatrics.svg"

  plotList <- list()
  for (i in 1:12) {
    plotList[[i]] <- ggally_text(paste("Plot #", i, sep = ""))
  }
  plotList[[1]] <- ggplot(na.omit(brexit),aes(Region,Pct_Leave))+
    geom_boxplot()+
    geom_hline(linetype = 2,yintercept = 50,color="red")+
    theme(axis.text.x = element_text(angle = 90, hjust = 1))

  plotList[[4]] <- ggplot(na.omit(brexit),aes(Region,Mean.Age))+
    geom_boxplot()+
    theme(axis.text.x = element_text(angle = 90, hjust = 1))

  plotList[[7]] <- ggplot(na.omit(brexit),aes(Region,UniQualification))+
    geom_boxplot()+
    theme(axis.text.x = element_text(angle = 90, hjust = 1))

  plotList[[10]] <- ggplot(na.omit(brexit),aes(Region,Fluent))+
    geom_boxplot()+
    theme(axis.text.x = element_text(angle = 90, hjust = 1))

  plotList[[2]] <- ggplot(na.omit(brexit),aes(NoQualification,Pct_Leave))+
    geom_boxplot()+
    geom_hline(linetype = 2,yintercept = 50,color="red")+
    theme(axis.text.x = element_text(angle = 90, hjust = 1))

  plotList[[5]] <- ggplot(na.omit(brexit),aes(NoQualification,Mean.Age))+
    geom_boxplot()+
    theme(axis.text.x = element_text(angle = 90, hjust = 1))

  plotList[[8]] <- ggplot(na.omit(brexit),aes(NoQualification,UniQualification))+
    geom_boxplot()+
    theme(axis.text.x = element_text(angle = 90, hjust = 1))

  plotList[[11]] <- ggplot(na.omit(brexit),aes(NoQualification,Fluent))+
    geom_boxplot()+
    theme(axis.text.x = element_text(angle = 90, hjust = 1))
    
  plotList[[3]] <- ggplot(na.omit(brexit),aes(Won.Parliament,Pct_Leave))+
    geom_boxplot()+
    geom_hline(linetype = 2,yintercept = 50,color="red")+
    theme(axis.text.x = element_text(angle = 90, hjust = 1))

  plotList[[6]] <- ggplot(na.omit(brexit),aes(Won.Parliament,Mean.Age))+
    geom_boxplot()+
    theme(axis.text.x = element_text(angle = 90, hjust = 1))

  plotList[[9]] <- ggplot(na.omit(brexit),aes(Won.Parliament,UniQualification))+
    geom_boxplot()+
    theme(axis.text.x = element_text(angle = 90, hjust = 1))

  plotList[[12]] <- ggplot(na.omit(brexit),aes(Won.Parliament,Fluent))+
    geom_boxplot()+
    theme(axis.text.x = element_text(angle = 90, hjust = 1))

  pm <- ggmatrix(
    plotList,
    nrow = 4, ncol = 3,
    yAxisLabels = c("Pct_Leave", "Mean.Age", "UniQualification","Fluent"),
    xAxisLabels = c("Region","NoQualification", "Won.Parliament"),
    title = "Matrix Title"
  )
  pm
#+END_SRC

#+RESULTS:
[[file:./pictures/QualQuanMatrics.svg]]
file:./pictures/QualQuanMatrics.svg

** Both quantitative 

#+BEGIN_SRC R :results graphics :file "./pictures/QuanMatrics.svg"
ggscatmat(brexit,columns = c ("Pct_Leave","Mean.Age","Fluent","UniQualification"),alpha = 0.5)  
#+END_SRC

#+RESULTS:
[[file:./pictures/QuanMatrics.svg]]

* TODO Inference (2 pages max., 1 pt)[0/4]
 - [ ] Confidence interval for a difference of two proportion.
 - [ ] Hypothesis testing for the equality of two proportions.
 - [ ] Confidence interval for a difference of two means.
 - [ ] Hypothesis testing for equality of two means.
 
** London lower UKIP than...

* TODO Sampling (2 pages max., 1.5 pt)[0/2]
 - [ ] Treat your data as the population of interest and take a stratified sample using as strata the categories of one of the qualitative variable and applying simple random sampling within each strata. You first need to decide the total sample size. Secondly, you need to allocate this total sample size in the strata. Comment on the common methods for sample allocation that exist in the literature. Select your preferred method (justify your decision) and obtain the sample size within each stratum.
 - [ ] With the sample drawn in 7.1, estimate unbiasedly the population mean of a quantitative variable of interest. Estimate unbiasedly the population proportion of a qualitative variable. With the sample drawn in 7.1, estimate unbiasedly the means of a quantitative variable of interest for each stratum. Estimate unbiasedly the proportion of a qualitative variable for each stratum.
 - use random sample

* TODO Model selection (1 page max., 1 pt)[0/3]
 - [ ] Select the best probability distribution for at least one variable of interest. You might need to take some transformation (e.g. log).
 - [ ] Estimate the parameters of the distribution by the method of moments or by maximum likelihood.

* TODO Conclusions (2 pages max., 1.5 pt)[0/2]
 - [ ] Summarize the most important conclusions of your analyses.
 - [ ] Mention limitations and possible extensions of this project.

* References (if needed)
  List of documents referred to in the text of the report.
  


* IMPORTANT REMARKS:
- Free statistical analysis: Additional statistical analyses selected by the student that do not fit in the general structure listed above might be included. The maximum pages for this additional material will be 3. This material will be evaluated with a maximum of 2 additional points only if it is reasonable, correct and related with this subject.
- All tables, plots and statistical procedures must be clearly described (what are you doing, what is it in the x and y axis, etc) and conclusions (interesting or useful information) must be drawn from all of them. Tables and figures without any comment must be removed from the project report. If new plots that are different from those studied in class are included, they must be very clearly explained.
- These projects will be carefully read and graded. The redaction of the report must be original (do not copy any paragraph from any source unless you explicitly acknowledged it by including a reference to the original source). English expression must be understandable and clean of typos or grammar errors (e.g. –s in third person singular).
- Do not include the whole list of data in the Project report.



