#+BEGIN_SRC R :session
library(magrittr)
library(dplyr)

#+END_SRC

#+RESULTS:
| dplyr     |
| magrittr  |
| stats     |
| graphics  |
| grDevices |
| utils     |
| datasets  |
| methods   |
| base      |


* Introduction
** Describe briefly the topic of the Project and the motivations (which kind of information or evidences would you like to find out). 
** Describe briefly the data set: source and what are the data about. 
** Define what is your target population and what is your sample (in the case that they are different). Give the total sample size.


* Description of variables and recoding
- Describe each of the variables that you will analyze in this project. What are they and how are they measured. 
- Mention the type of each variable, saying if it is qualitative or quantitative, and depending on the case, nominal/ordinal or discrete/continuous. 
- For variables with too many categories, try to reduce the number of categories by merging categories with similar meaning and recoding them. With fewer categories, interpretation is easier.

** Qualitative or categorical data 
- Party voted at last European parliament election
- Region
- Young/old population from mean age
** Quantitative continuous data
- % leave vote
- % main language is not English
- % no qualification
- % with university degree
** Merging
| Region   | Area  | EPE | English% | NoQual% | Uni% | Age.mean | Leave% |
|----------+-------+-----+----------+---------+------+----------+--------|
| Scotland | Angus | Con | %        | %       | %    |       35 | %      |

#+BEGIN_SRC R :session
  parliament <- read.table("data/parliament.csv",header=F,skip=16,sep=",",nrows=401)[,c(1,6,7,8,9,10,11,12)]
  colnames(parliament) <- c("Area","Con","Lab","LD","UKIP","Green","BNP","SNP")
  parliament$SNP <- as.integer(as.character(parliament$SNP))
  winning.party <- function(region){
  
  return(names(which.max(region)))

  }
  
  parliament$Won <- apply(parliament, 1, winning.party)%>%
  lapply(function(x) ifelse(is.null(x), NA, x))%>%
  unlist()

  head(parliament)

  #+End_SRC

#+RESULTS:
| ABERDEEN CITY       |  9824 | 12420 | 4605 | 5025 | 3723 | 375 | 15412 | SNP |
| ABERDEENSHIRE       | 15710 |  6402 | 8876 | 7420 | 3612 | 576 | 19802 | SNP |
| ANGUS               |  7534 |  3768 | 1486 | 3200 | 1574 | 237 | 11044 | SNP |
| ARGYLL & BUTE       |  5191 |  3695 | 5174 | 3030 | 1912 | 195 |  7792 | SNP |
| CLACKMANNANSHIRE    |  1624 |  3825 |  443 | 1218 |  736 | 100 |  4074 | SNP |
| DUMFRIES & GALLOWAY | 14143 |  8909 | 1808 | 5752 | 2418 | 363 |  8634 | Con |




#+BEGIN_SRC R :session
  age <- read.csv("data/age.csv")[-1,]%>%
  select(GEO_LABEL,F184,F185)
  colnames(age) <- c("Area","Mean","Median")
  head(age)
#+END_SRC


#+RESULTS:
| Antrim     | 36.72 | 36 |
| Ards       | 40.04 | 41 |
| Armagh     | 37.09 | 36 |
| Ballymena  | 39.19 | 39 |
| Ballymoney |  37.7 | 37 |
| Banbridge  | 37.13 | 37 |

#+BEGIN_SRC R :session
  qualification <-  read.csv("data/qualification.csv")[-1,]%>%
  select(GEO_LABEL,F186,F187,F192)
  qualification$NoQualification <- round(100 * as.numeric(as.character(qualification$F187))/as.numeric(as.character(qualification$F186)))
  qualification$UniQualification <- round(100 * as.numeric(as.character(qualification$F192))/as.numeric(as.character(qualification$F186)))
  qualification <- select(qualification,GEO_LABEL,NoQualification,UniQualification)
  colnames(qualification)[1] <- "Area"
  head(qualification)
#+END_SRC

#+RESULTS:
| Antrim     | 26 | 24 |
| Ards       | 27 | 22 |
| Armagh     | 30 | 22 |
| Ballymena  | 31 | 22 |
| Ballymoney | 33 | 18 |
| Banbridge  | 28 | 24 |

Proficiency in Northern Ireland and Scotland has been measured differently. Scotland were not asked if English is there main language but instead if they speak Very well, Well, or not at all. In Northern Ireland, they were only asked if English was their main language. In England they were asked if English or Welsh in Wales was their main language. English might include americans.

We will only use proficiency from England.

#+BEGIN_SRC R :session
  english <- read.csv("data/english.csv")[-1,]%>%
  select(GEO_LABEL,F792,F793,F86631,F322322,F322718)
  english_England <- english[as.character(english$F86631)!="",]
  english_England$Fluent <- round(100 * as.numeric(as.character(english_England$F793)) / as.numeric(as.character(english_England$F792)))

  english_Scotland<- english[as.character(english$F322322)!="",]
  english_Scotland$Fluent <- round(100 * as.numeric(as.character(english_Scotland$F322322)) / as.numeric(as.character(english_Scotland$F792)))
  
  english_Ireland <- english[as.character(english$F322718)!="",]
  english_Ireland <- data.frame(GEO_LABEL="Northern Ireland",Fluent=round(100 * sum(as.numeric(as.character(english_Ireland$F322718)))/sum(as.numeric(as.character(english_Ireland$F792)))))
  
  english <- rbind(select(english_England,GEO_LABEL,Fluent),select(english_Scotland,GEO_LABEL,Fluent))%>%
  rbind(english_Ireland)

  colnames(english)[1] <- "Area"
  head(english)
#+END_SRC

#+RESULTS:
| Hartlepool           | 99 |
| Middlesbrough        | 95 |
| Redcar and Cleveland | 99 |
| Stockton-on-Tees     | 98 |
| Darlington           | 97 |
| Halton               | 99 |

#+BEGIN_SRC R :session
  brexit <- read.csv("data/result.csv")%>%
  select(Region,Area_Code,Area,Pct_Remain,Pct_Leave)
  head(brexit)
#+END_SRC

#+RESULTS:
| East | E06000031 | Peterborough         | 39.11 | 60.89 |
| East | E06000032 | Luton                | 43.45 | 56.55 |
| East | E06000033 | Southend-on-Sea      | 41.92 | 58.08 |
| East | E06000034 | Thurrock             | 27.72 | 72.28 |
| East | E06000055 | Bedford              | 48.22 | 51.78 |
| East | E06000056 | Central Bedfordshire | 43.87 | 56.13 |

#+BEGIN_SRC R :session
  # merge age, english, qualification
  census <- inner_join(age,qualification,by = "Area")%>%
    left_join(english,by = "Area")
  head(census)

#+END_SRC

#+RESULTS:
| Antrim     | 36.72 | 36 | 26 | 24 | nil |
| Ards       | 40.04 | 41 | 27 | 22 | nil |
| Armagh     | 37.09 | 36 | 30 | 22 | nil |
| Ballymena  | 39.19 | 39 | 31 | 22 | nil |
| Ballymoney |  37.7 | 37 | 33 | 18 | nil |
| Banbridge  | 37.13 | 37 | 28 | 24 | nil |

Some regions are counted together in the data from inFuse 2011.
- City of London, Westminster
- Cornwall, Isles of Scilly

#+BEGIN_SRC R :session
  levels(brexit$Area)[!(levels(brexit$Area)%in%levels(age$Area))]
#+END_SRC

#+RESULTS:
| City of London    |
| Cornwall          |
| Gibraltar         |
| Isles of Scilly   |
| Northern Ireland  |
| Vale of Glamorgan |

Northern Ireland areas are counted together

#+BEGIN_SRC R :session
  levels(age$Area)[!(levels(age$Area)%in%levels(brexit$Area))]
#+END_SRC

#+RESULTS:
|                           |
| Antrim                    |
| Ards                      |
| Armagh                    |
| Ballymena                 |
| Ballymoney                |
| Banbridge                 |
| Belfast                   |
| Carrickfergus             |
| Castlereagh               |
| Coleraine                 |
| Cookstown                 |
| Cornwall, Isles of Scilly |
| Craigavon                 |
| Derry                     |
| Down                      |
| Dungannon                 |
| Fermanagh                 |
| Larne                     |
| Limavady                  |
| Lisburn                   |
| Magherafelt               |
| Moyle                     |
| Newry and Mourne          |
| Newtownabbey              |
| North Down                |
| Omagh                     |
| Strabane                  |
| The Vale of Glamorgan     |

* Univariate description
** Qualitative variables: Frequency tables, Barplots or Piechars. 
** Quantitative variables: Frequency tables (intervals if continuous). Location measures (mean, median, quartiles), dispersion measures (variance, std. dev., CV, range, IQR), shape measures (asymmetry coefficients), Histogram or Boxplot.
* Bivariate description
** Both variables qualitative: Crossclassified table, tables with interesting conditional distributions, grouped or stacked barplots for those conditionals. Compare proportions in different groups. 
** One qualitative, one quantitative: Compare the means, variances and CVs of the quantitative variable for each category of the other one. Compare histograms or boxplots of the quantitative variable for each category of the other one. 
** Both quantitative: scatterplot, covariance, Pearson correlation coef., regression line of a target variable in terms of one/several explanatory variables.
* Inference
** Confidence interval for a difference of two proportion. 
** Confidence interval for a difference of two means. 
** Hypothesis testing for the equality of two proportions. 
** Hypothesis testing for equality of two means.
* Sampling
** Treat your data as the population of interest and take a stratified sample using as strata the categories of one of the qualitative variable and applying simple random sampling within each strata. You first need to decide the total sample size. Secondly, you need to allocate this total sample size in the strata. Comment on the common methods for sample allocation that exist in the literature. Select your preferred method (justify your decision) and obtain the sample size within each stratum.
** With the sample drawn in 7.1, estimate unbiasedly the population mean of a quantitative variable of interest. Estimate unbiasedly the population proportion of a qualitative variable. 
** With the sample drawn in 7.1, estimate unbiasedly the means of a quantitative variable of interest for each stratum. Estimate unbiasedly the proportion of a qualitative variable for each stratum.
* Model selection
** Select the best probability distribution for at least one variable of interest. You might need to take some transformation (e.g. log).
** Estimate the parameters of the distribution by the method of moments or by maximum likelihood.
* Conclusions
** Select the best probability distribution for at least one variable of interest. You might need to take some transformation (e.g. log). 
** Estimate the parameters of the distribution by the method of moments or by maximum likelihood.
* References
